---
- name: configure machine for wordpress web server
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    wp_dir: "${WPDIR}"
    admin_mail: "${ADMIN_MAIL}"
  tasks:
    - name: install needed software
      yum:
        name:
          - httpd
          - python2-pip
          - mysql
        state: installed
    - name: install pip packages
      pip:
        name:
          - boto3
          - botocore
    - name: collect data from ssm
      set_fact:
        wp_db: "{{ lookup('aws_ssm', '${WP_DB_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
        wp_db_name: "{{ lookup('aws_ssm', '${WP_DB_NAME_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
        wp_admin: "{{ lookup('aws_ssm', '${WP_ADMIN_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
        wp_blog: "{{ lookup('aws_ssm', '${WP_BLOG_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
      no_log: True
    - name: install and configure wordpress
      shell: "{{ item }}"
      with_items:
        - "amazon-linux-extras install -y epel php7.3"
        - "yum install -y wp-cli"
        - "/usr/bin/wp --path={{ wp_dir }} core download"
        - "/usr/bin/wp --path={{ wp_dir }} core config --dbname={{ wp_db_name.name }} --dbuser={{ wp_db.user }} --dbpass=\'{{ wp_db.password }}\' --dbhost={{ wp_db_name.host }} --dbprefix=wp_"
        - "/usr/bin/wp --path={{ wp_dir }} core install --url={{ wp_db.url }} --title=wordpress --admin_user={{ wp_admin.user }} --admin_password=\'{{ wp_admin.password }}\' --admin_email={{ admin_mail }}"
      no_log: True
    - name: fix directories permissions
      file:
        path: "{{ wp_dir }}"
        recurse: yes
        owner: ec2-user
        group: apache
        mode: u=rwX,g=rwX,o=rX
    - name: start httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
    - name: update post
      shell: |
        wp post update 1 --path="{{ wp_dir }}" --post_content="{{ wp_blog.post1 }}" --post_title="Linux namespaces" --post_name="Linux namespaces" --post_status=publish --post_author="{{ wp_admin.user }}"
        wp comment delete 1 --path="{{ wp_dir }}"


