---
- name: configure db host
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - db_dir: "${DB_ROOT_DIR}"
    - mysql_user: "mysql"
    - mysql_group: "mysql"
    - project: "${PROJECT}"
  tasks:
    - name: create file system
      filesystem:
        dev: /dev/xvdh
        fstype: ext4
    - name: mount FS
      mount:
        src: /dev/xvdh
        path: '{{ db_dir }}'
        state: mounted
        fstype: ext4
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python2-pip
        state: installed
    - name: chown_db_dir
      file:
        path: '{{ db_dir }}'
        owner: '{{ mysql_user }}'
        group: '{{ mysql_group }}'
        mode: '1755'
    - name: start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: install pip
      pip:
        name:
          - boto3
          - botocore
          - PyMySQL
    - name: ssm data
      set_fact:
        db_root: "{{ lookup('aws_ssm', '${DB_ROOT_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
        wp_db: "{{ lookup('aws_ssm', '${WP_DB_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
        wp_db_name: "{{ lookup('aws_ssm', '${WP_DB_NAME_SSM}', region='${REGION}', shortnames=true, bypath=true, recursive=true) }}"
      no_log: True
    - name: get facts
      uri:
        url: "http://169.254.169.254/latest/dynamic/instance-identity/document"
        return_content: true
        headers:
          Content-type: "application/json"
      register: result
    - name: set hostname
      hostname:
        name: "{{ result.json.instanceId }}"
    - name: set tag
      shell: |
        aws ec2 create-tags --region "{{ result.json.region }}" --resources "{{ result.json.instanceId }}" --tags Key=Name,Value="{{ project }}-{{ result.json.pendingTime }}"
    - name: create db and user
      block:
        - name: connect localhost
          mysql_db:
            login_user: "{{ wp_db.user }}"
            login_password: "{{ wp_db.password }}"
            name: "{{ wp_db_name.name }}"
            connect_timeout: 10
      rescue:
        - name: create DB admin
          mysql_user:
            check_implicit_admin: yes
            connect_timeout: 10
            name: "{{ db_root.user }}"
            password: "{{ db_root.password }}"
            priv: "*.*:ALL,GRANT"
            state: present
        - name: create DB
          mysql_db:
            login_user: "{{ db_root.user }}"
            login_password: "{{ db_root.password }}"
            name: "{{ wp_db_name.name }}"
            state: present
        - name: create user
          mysql_user:
            check_implicit_admin: yes
            name: "{{ wp_db.user }}"
            password: "{{ wp_db.password }}"
            priv: "{{ wp_db_name.name }}.*:ALL,GRANT"
            host: "{{ item }}"
            state: present
          with_items:
            - "%"
            - "localhost"
